/*
 * This source file was generated by the Gradle 'init' task
 */
package caso1;

import caso1.model.Producto;
import caso1.services.InventarioService;
import caso1.util.ValidadorEntrada;

public class App {

    public static void main(String[] args) {
        InventarioService inventarioService = new InventarioService();
        int opcion;
        do {
            mostrarMenu();
            opcion = ValidadorEntrada.leerEntero("Seleccione una opción: ");
            switch (opcion) {
                case 1:
                    agregarProducto(inventarioService);
                    break;
                case 2:
                    eliminarProducto(inventarioService);
                    break;
                case 3:
                    inventarioService.mostrarInventario();
                    break;
                case 4:
                    String codigo = ValidadorEntrada.leerCadena("Ingrese el código del producto a buscar: ");
                    inventarioService.buscarProducto(codigo)
                        .ifPresentOrElse(
                            Producto::mostrarProducto,
                            () -> System.out.println("Producto no encontrado.")
                        );
                    break;
                case 5:
                    actualizarProducto(inventarioService);
                    break;
                case 0:
                    System.out.println("Saliendo del sistema...");
                    break;
                default:
                    System.out.println("Opción inválida. Por favor, intente de nuevo.");
            }
        } while (opcion != 0);
            

    }

    private static void mostrarMenu() {
        System.out.println("=== Sistema de Inventario ===");
        System.out.println("1. Agregar Producto");
        System.out.println("2. Eliminar Producto");
        System.out.println("3. Mostrar Inventario");
        System.out.println("4. Buscar Producto");
        System.out.println("5. Actualizar Producto");
        System.out.println("0. Salir");
        System.out.print("Seleccione una opción: ");
    }

    private static void agregarProducto(InventarioService inventarioService) {
        System.out.println("--- Agregar Producto ---");
        String codigo = ValidadorEntrada.leerCadena("Ingrese el código del producto: ");
        String nombre = ValidadorEntrada.leerCadena("Ingrese el nombre del producto: ");
        double precio = ValidadorEntrada.leerDouble("Ingrese el precio del producto: ");
        int cantidad = ValidadorEntrada.leerEntero("Ingrese la cantidad del producto:");
        inventarioService.agregarProducto(new Producto(codigo, nombre, precio, cantidad));
    }

    private static void eliminarProducto(InventarioService inventarioService) {
        System.out.println("--- Eliminar Producto ---");
        String codigo = ValidadorEntrada.leerCadena("Ingrese el código del producto a eliminar: ");
        inventarioService.eliminarProducto(codigo);
    }

    private static void actualizarProducto(InventarioService inventarioService) {
        System.out.println("--- Actualizar Producto ---");
        String codigo = ValidadorEntrada.leerCadena("Ingrese el código del producto a actualizar: ");
        String nombre = ValidadorEntrada.leerCadena("Ingrese el nuevo nombre del producto: ");
        double precio = ValidadorEntrada.leerDouble("Ingrese el nuevo precio del producto: ");
        int cantidad = ValidadorEntrada.leerEntero("Ingrese la nueva cantidad del producto:");
        inventarioService.actualizarProducto(codigo, new Producto(codigo, nombre, precio, cantidad));
    }

}
